### ISSUE TITLE
Memory leak warning despite not seemingly creating circular references

### ISSUE THREAD

**Issue by perlancar** [FGasper/p5-JavaScript-QuickJS#2]
A simple one-liner produces memory leak warning:

    $ perl -MJavaScript::QuickJS -E'$js=JavaScript::QuickJS->new; say $js->eval("1+1")'
    2
    DESTROYing JavaScript::QuickJS=SCALAR(0x55ddac38d5e8) at global destruction; memory leak likely!

while this admittedly does not:

    $ perl -MJavaScript::QuickJS -E'JavaScript::QuickJS->new>eval("1+1")'
    2

as well as this:

    $ perl -MJavaScript::QuickJS -E'my $js=JavaScript::QuickJS->new; say $js->eval("1+1")'
    2

The doc says:

    If any instance of a class of this distribution is DESTROY()ed at Perl’s global destruction, we assume that this is a memory leak, 
    and a warning is thrown. To prevent this, avoid circular references.

It is unclear how the first code creates "circular references". Perhaps the doc needs some rewording?

**Comment by FGasper** [comment]
The doc is fine; you created $js as a global. Prefix it with `my` to see the issue go away.

**Comment by perlancar** [comment]
> The doc is fine; you created $js as a global. Prefix it with my to see the issue go away.

I did. My issue is with "To prevent this, avoid circular references." sentence. Did I create a circular reference by not prefixing the variable with `my`?

**Comment by FGasper** [comment]
> Did I create a circular reference by not prefixing the variable with my?

Ahh ok, I take your meaning. Yeah that text could be improved.

**Comment by FGasper** [comment]
@perlancar How’s this?
https://github.com/FGasper/p5-JavaScript-QuickJS/pull/3/files

**Comment by perlancar** [comment]
Now that I think of it, those two sentences describe two issues. I'm proposing some rewording in a PR.
