### ISSUE TITLE
RFE: Add Date support

### ISSUE THREAD

**Issue by perlancar** [FGasper/p5-JavaScript-QuickJS#5]
% perl -MJavaScript::QuickJS -MData::Dump -E'dd( JavaScript::QuickJS->new->eval("new Date") )'
    {}

**Comment by FGasper** [comment]
It wouldn’t be overly hard to do this; I just haven’t had the need. It would be much like this module’s RegExp implementation, if you want to take a crack at it?

**Comment by FGasper** [comment]
A provisional Date implementation is in master. Please try it out.

**Comment by perlancar** [comment]
Ah wow, that was quick. Thanks!
