### ISSUE TITLE
Crash when importing from 'os'

### ISSUE THREAD

**Issue by sciurius** [FGasper/p5-JavaScript-QuickJS#6]
I have problems importing from os. The following snippet crashes with Segmentation fault,
````
use JavaScript::QuickJS;

my $js = JavaScript::QuickJS->new->std->os->helpers;

$js->eval_module( "import * as os from 'os'" );
````
Fedora 37.

**Comment by FGasper** [comment]
Confirmed. One-liner:
```
perl -Mblib -MJavascript::QuickJS -e'my $js = JavaScript::QuickJS->new->std->os->helpers; $js->eval_module( q<import * as os from "os"> );'
```

**Comment by FGasper** [comment]
@sciurius Try [this PR](https://github.com/FGasper/p5-JavaScript-QuickJS/pull/7). If it works for you, I’ll merge & rerelease.

Thank you!

**Comment by FGasper** [comment]
Fixed upstream.

**Comment by sciurius** [comment]
I'm not sure if this is related but I still get some strange things.

I use a javascript program abc2svg (https://chiselapp.com/user/moinejf/repository/abc2svg/doc/trunk/README.md) that I call using a wrapper script `chordproabc.js`. This works fine:
````
$ qjs --std chordproabc.js lib/abc2svg foo.html foo.abc
````

Unlike the qjs `--std` option, the JavaScript::QuickJS std() method enables but does not import. So I add two import lines
````
import * as std from 'std'
import * as os  from 'os'
````
Now the script fails somewhere in the guts of abc2svg. It doesn't matter whether I import something or everything from std or os, as soon as I have an import it fails.

This is reproducible with qjs, when I invoke the script with the imports:
````
$ qjs --std chordproabc.js lib/abc2svg foo.html foo.abc
TypeError: not a function
    at abc_cmd (lib/abc2svg/cmdline.js:148)
    at <anonymous> (chordproabc.js:77)
````

I don't have a clue what is going on. Do you? Why the difference between `--std` and `-->std()`?

I've attached a zip with the necessary files to reproduce this.
Thanks in advance.
[qq.zip](https://github.com/FGasper/p5-JavaScript-QuickJS/files/13509629/qq.zip)

**Comment by FGasper** [comment]
@sciurius Can you please open a separate issue for this?
