### ISSUE TITLE
Compatibility with QuickJS 2024-01-13

### ISSUE THREAD

**Issue by Cellesti** [FGasper/p5-JavaScript-QuickJS#9]
Hello, [QuickJS 2024-01-13](https://bellard.org/quickjs/Changelog) has been released, and while trying to compile JavaScript::QuickJS with it, i came across some errors in the tests:
```
#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/import_os.t line 18.
# Warning was 'UNEXPECTED: Discarding non-null return from ES module: HASH(0x7ff76d30dd50) at t/import_os.t line 18.'
#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/import_os.t line 18.
# Warning was 'UNEXPECTED: Discarding non-null return from ES module: HASH(0x7ff76d30de70) at t/import_os.t line 18.'
# Looks like you failed 2 tests of 10.
t/import_os.t ............... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/10 subtests 
t/import_std.t .............. ok
#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/import_std2.t line 29.
# Warning was 'UNEXPECTED: Discarding non-null return from ES module: HASH(0x7f9d84629b08) at t/import_std2.t line 29.'
# Looks like you failed 1 test of 2.
t/import_std2.t ............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
```

The test at t/module.t line 74 also fails in the same way. I think this is probably caused by `JS_Eval` now returning a promise if the `JS_EVAL_TYPE_MODULE` flag is set.

I know compiling with any other QuickJS version than the one bundled together with JavaScript::QuickJS is unsupported, so may i know if there are plans to update the bundled QuickJS?

Thank you.

**Comment by FGasper** [comment]
I have no _direct_ plans to update QJS, though I’ve seen the project’s recent flurry of activity.

I can see 2 ways of supporting this:
1. Just discard & clean up the promise. This should be easy.
2. Teach JS::QJS to return it. This will involve creating a JavaScript::QuickJS::Promise class. It may be nontrivial because of the callbacks involved.

Are you able to take a stab implementing the first solution? I haven’t looked at the new behaviour; what does the returned promise give us?

**Comment by FGasper** [comment]
FYI: I don’t actually _use_ JS::QJS myself (nor do much with Perl at all) anymore, but I’m still maintaining it.

**Comment by FGasper** [comment]
I tried it just now … it should be just as simple as commenting out the block that throws the warning.

Will that work for you?

**Comment by Cellesti** [comment]
Thanks for looking into the issue.

Commenting out the block that throws the warning allows the tests to pass, so i guess it would work.

As for what the promise returns, based on [these lines from QuickJS's run-test262.c](https://github.com/bellard/quickjs/blob/3f81070e573e3592728dbbbd04c84c498b20d6dc/run-test262.c#L1215-L1221), it looks like it is just more ways of returning an error in case the promise is not fulfilled.

**Comment by FGasper** [comment]
I’ve uploaded version 0.19_91, which fixes this issue (and includes a Promise wrapper).

Please test it if you can. Thanks!

**Comment by Cellesti** [comment]
Thank you, just tested 0.19_91, and it's good :)
